config/routes.rb
Rails.application.routes.draw do
  resources :food_items

  root 'welcome#index'

end

app/models/food_item.rb
class FoodItem < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/food_items/_form.html.erb
<%= form_for @food_item, :html => {:multipart => true} do |f| %>
  <% if @food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% @food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing food_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<h1>Listing food_items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New food_item</h1>

<%= render 'form' %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_item.name %>
</p>

<%= link_to 'Edit', edit_food_item_path(@food_item) %> |
<%= link_to 'Back', food_items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VenueSpace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<!-- <h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p> -->

<p>Hello World!</p>
<p>Image Uploader</p>